In [365]:
import pandas as pd 
import numpy as np

# I. DF

In [366]:
df_mk = pd.read_excel('./dataset_2nd/mkcap_update.xlsx', index_col=0) # 시가총액
df_ale = pd.read_excel('./dataset_2nd/df_finance_final_new_code.xlsx', index_col=0)

In [367]:
df_ale

,회사명,거래소코드,회계년도,유동비율(IFRS),당좌비율(IFRS),유동부채비율(IFRS),비유동비율(IFRS),순운전자본비율(IFRS),부채비율(IFRS),차입금의존도(IFRS),...,이익잉여금비율_개별,이익잉여금비율_연결,총자산회전율_개별,총자산회전율_연결,총자산_증가율_개별,총자산_증가율_연결,외화_부채율_개별,외화_부채율_연결,상장일,상장폐지일
0,(주)CMG제약,58820,2011/12,200.32,164.32,41.66,67.16,27.75,50.61,16.74,...,100.000000,100.000000,-1.775170e+09,-1.775170e+09,NaN,NaN,24138,24138,2001/08/31,NaN
1,(주)CMG제약,58820,2012/12,706.26,661.93,21.09,31.37,70.91,80.33,34.21,...,-195.095818,-196.665332,3.845739e+01,3.851384e+01,-4.226857e+07,-4.220662e+07,26525,26525,2001/08/31,NaN
2,(주)CMG제약,58820,2013/12,695.84,611.84,11.21,36.09,58.54,14.10,2.53,...,-129.596096,-129.773360,3.598424e+01,3.610340e+01,3.361017e-01,3.388967e-01,114956,114956,2001/08/31,NaN
3,(주)CMG제약,58820,2014/12,325.47,269.08,17.76,60.67,33.80,18.46,2.65,...,-106.488657,-106.730325,3.988577e+01,3.992351e+01,1.007961e-02,8.496602e-03,-25644,-25644,2001/08/31,NaN
4,(주)CMG제약,58820,2015/12,297.75,236.06,18.87,64.56,30.90,20.74,0.00,...,-113.277958,-113.566459,4.714455e+01,4.719306e+01,5.525104e-03,5.441772e-03,6213,6213,2001/08/31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17482,흥구석유(주),24060,2018/12,329.17,290.09,5.40,89.00,11.59,6.76,0.00,...,48.109706,NaN,2.142997e+02,NaN,-2.471926e-02,NaN,0,0,1994/12/07,NaN
17483,흥구석유(주),24060,2019/12,485.39,422.76,6.05,79.27,21.47,8.65,0.00,...,50.690910,NaN,1.896790e+02,NaN,2.417161e-02,NaN,0,0,1994/12/07,NaN
17484,흥구석유(주),24060,2020/12,1108.08,1013.02,3.14,70.39,30.09,5.18,0.50,...,53.574462,NaN,1.372228e+02,NaN,5.360309e-02,NaN,0,0,1994/12/07,NaN
17485,흥구석유(주),24060,2021/12,913.64,818.58,3.68,71.15,28.57,4.75,0.44,...,54.129465,NaN,1.589409e+02,NaN,-6.060298e-03,NaN,0,0,1994/12/07,NaN
17486,흥구석유(주),24060,2022/12,185.24,115.48,5.84,106.47,4.25,17.29,9.74,...,54.269722,NaN,1.661754e+02,NaN,6.138945e-02,NaN,0,0,1994/12/07,NaN

In [368]:
df_ale.columns

Index(['회사명', '거래소코드', '회계년도', '유동비율(IFRS)', '당좌비율(IFRS)', '유동부채비율(IFRS)',
       '비유동비율(IFRS)', '순운전자본비율(IFRS)', '부채비율(IFRS)', '차입금의존도(IFRS)',
       '비유동장기적합률(IFRS)', '자기자본순이익률(IFRS)', '총자본순이익률(IFRS)',
       '자기자본정상영업이익률(IFRS)', '총자본정상영업이익률(IFRS)', '경영자본순이익률(IFRS)',
       '매출액순이익률(IFRS)', '이자보상배율(이자비용)(IFRS)', '금융비용부담률(IFRS)',
       '매출액정상영업이익률(IFRS)', '당좌자산회전률(IFRS)', '재고자산회전률(IFRS)', '자기자본회전률(IFRS)',
       '경영자본회전률(IFRS)', '매출채권회전률(IFRS)', '매입채무회전률(IFRS)', '유형자산회전율(IFRS)',
       '매출액증가율(IFRS)', '순이익증가율(IFRS)', '정상영업이익증가율(IFRS)', '유동자산증가율(IFRS)',
       '[제조]유동비율(IFRS연결)', '[제조]당좌비율(IFRS연결)', '[제조]유동부채비율(IFRS연결)',
       '[제조]비유동비율(IFRS연결)', '[제조]순운전자본비율(IFRS연결)', '[제조]부채비율(IFRS연결)',
       '[제조]차입금의존도(IFRS연결)', '[제조]비유동장기적합률(IFRS연결)', '[제조]자기자본순이익률(IFRS연결)',
       '[제조]총자본순이익률(IFRS연결)', '[제조]자기자본정상영업이익률(IFRS연결)',
       '[제조]총자본정상영업이익률(IFRS연결)', '[제조]경영자본순이익률(IFRS연결)', '[제조]매출액순이익률(IFRS연결)',
       '[제조]이자보상배율(이자비용)(IFRS연결)', '[제조]금융비용부담률(IFRS연결)',
       '[제조]매출액정상영업이익률(IFRS연결)', '[제조]당좌자산회전률(IFRS연결)', '[제조]재고자산회전률(IFRS연결)',
       '[제조]자기자본회전률(IFRS연결)', '[제조]경영자본회전률(IFRS연결)', '[제조]매출채권회전률(IFRS연결)',
       '[제조]매입채무회전률(IFRS연결)', '[제조]유형자산회전율(IFRS연결)', '[제조]매출액증가율(IFRS연결)',
       '[제조]순이익증가율(IFRS연결)', '[제조]정상영업이익증가율(IFRS연결)', '[제조]유동자산증가율(IFRS연결)',
       '평균총자산_개별', '평균총부채_개별', '평균이익잉여금_개별', '평균총자본_개별',
       '[제조]매출액(수익)(*)(IFRS)', '평균총자산', '평균총부채', '평균이익잉여금', '평균총자본',
       '[제조]매출액(수익)(*)(IFRS연결)', 'CASH FLOW 대 부채비율(IFRS)', '총자본투자효율(IFRS)(천원)',
       '[제조]CASH FLOW 대 부채비율(IFRS연결)', '[제조]총자본투자효율(IFRS연결)', 'spread(%)',
       'PPI(2015기준)', '실질GDP성장률(%)', '청산가치율_개별', '청산가치율_연결', '이익잉여금비율_개별',
       '이익잉여금비율_연결', '총자산회전율_개별', '총자산회전율_연결', '총자산_증가율_개별', '총자산_증가율_연결',
       '외화_부채율_개별', '외화_부채율_연결', '상장일', '상장폐지일'],
      dtype='object')

In [369]:
col_list = ['회사명', '거래소코드', '회계년도',
            '평균총자산_개별', '평균총부채_개별','평균총자본_개별','평균이익잉여금_개별',
            '평균총자산', '평균총부채','평균총자본','평균이익잉여금'
            ]

In [370]:
df_ale_copy = df_ale.copy()

In [371]:
df_ale = df_ale[col_list]

In [372]:
# 2011 값 : -1 or NaN -> 2011 값으로 대체 예정 
df_ale.loc[df_ale['회계년도'].str.contains('2011')]

,회사명,거래소코드,회계년도,평균총자산_개별,평균총부채_개별,평균총자본_개별,평균이익잉여금_개별,평균총자산,평균총부채,평균총자본,평균이익잉여금
0,(주)CMG제약,58820,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
12,(주)ES큐브,50120,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
24,(주)가비아,79940,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
51,(주)강원에너지,114190,2011/11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,(주)고영테크놀러지,98460,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...
17418,화일약품(주),61250,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
17430,휴림네트웍스(주),192410,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
17442,휴림로봇(주),90710,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
17463,휴젤(주),145020,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
17475,흥구석유(주),24060,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [373]:
df_2011 = df_ale.loc[df_ale['회계년도'].str.contains('2011')]

In [374]:
df_2011

,회사명,거래소코드,회계년도,평균총자산_개별,평균총부채_개별,평균총자본_개별,평균이익잉여금_개별,평균총자산,평균총부채,평균총자본,평균이익잉여금
0,(주)CMG제약,58820,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
12,(주)ES큐브,50120,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
24,(주)가비아,79940,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
51,(주)강원에너지,114190,2011/11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,(주)고영테크놀러지,98460,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...
17418,화일약품(주),61250,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
17430,휴림네트웍스(주),192410,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
17442,휴림로봇(주),90710,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
17463,휴젤(주),145020,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
17475,흥구석유(주),24060,2011/12,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [375]:
df_2011.loc[df_2011["평균총자산_개별"].isna()] # 결산월 Not 12월 -> 무시

,회사명,거래소코드,회계년도,평균총자산_개별,평균총부채_개별,평균총자본_개별,평균이익잉여금_개별,평균총자산,평균총부채,평균총자본,평균이익잉여금
51,(주)강원에너지,114190,2011/11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2233,(주)메디콕스,54180,2011/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2524,(주)바른손,18700,2011/03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2873,(주)비덴트,121800,2011/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3002,(주)비츠로셀,82920,2011/03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3014,(주)비츠로시스,54220,2011/03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3026,(주)비츠로테크,42370,2011/03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3893,(주)소프트센,32680,2011/09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4847,(주)아이씨디,40910,2011/09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7123,(주)와이오엠,66430,2011/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8311,(주)이크레더블,92130,2011/09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8917,(주)제이와이피엔터테인먼트,35900,2011/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9086,(주)중앙에너비스,440,2011/09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9372,(주)천보,278280,2011/09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10990,(주)티피씨메카트로닉스,48770,2011/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12759,글로본(주),19660,2011/03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12933,농업회사법인(주)농우바이오,54050,2011/10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13736,바이온(주),32980,2011/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13786,부산방직공업(주),25270,2011/03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15757,위더스제약(주),330350,2011/06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17033,한국기업평가(주),34950,2011/09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17406,화성밸브(주),39610,2011/03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## I-I. DF 2011 값은 그대로 2011 값 쓰기

In [376]:
# 연결 ALE
df_a = pd.read_excel('./dataset_2nd/z_score_asset.xlsx')
df_l = pd.read_excel('./dataset_2nd/z_score_liability.xlsx')
df_e = pd.read_excel('./dataset_2nd/z_score_equity.xlsx')

df_ale_11 = pd.concat([df_a, df_l, df_e], axis=1) # 회사명, 거래소코드, 회계년도 제거 필요 

# 연결 Sales & R/E
df_sre = pd.read_excel('./dataset_2nd/z_score_sales_retainedearning.xlsx')

# 개별 ALE
df_ale_each = pd.read_excel('./dataset_2nd/z_score_ALE_each.xlsx')

# 개별 Sales & R/E
df_sre_each = pd.read_excel('./dataset_2nd/z_score_salesRE_each.xlsx')

In [377]:
# 11' 데이터프레임 정리 

df_ale_11.columns = ['회사명', '거래소코드', '회계년도', '[제조]자산(*)(IFRS연결)', '회사명2', '거래소코드2', '회계년도2',\
       '[제조]부채(*)(IFRS연결)', '회사명3', '거래소코드3', '회계년도3', '[제조]자본(*)(IFRS연결)(천원)']
df_ale_11.drop(['회사명2', '거래소코드2', '회계년도2','회사명3', '거래소코드3', '회계년도3'], axis = 1, inplace = True)

df_ale_each.drop(['회사명','거래소코드', '회계년도'], axis = 1, inplace = True)

df_sre.drop(['회사명','거래소코드', '회계년도'], axis = 1, inplace = True)
df_sre_each.drop(['회사명','거래소코드', '회계년도'], axis = 1, inplace = True)

In [378]:
df_11 = pd.concat([df_ale_11, df_ale_each, df_sre, df_sre_each], axis = 1)

In [379]:
df_11.columns

Index(['회사명', '거래소코드', '회계년도', '[제조]자산(*)(IFRS연결)', '[제조]부채(*)(IFRS연결)',
       '[제조]자본(*)(IFRS연결)(천원)', '[제조]자산(*)(IFRS)(천원)', '[제조]부채(*)(IFRS)(천원)',
       '[제조]자본(*)(IFRS)(천원)', '[제조]      이익잉여금(결손금)(*)(IFRS연결)(천원)',
       '[제조]매출액(수익)(*)(IFRS연결)(천원)', '[제조]   이익잉여금(결손금)(*)(IFRS)(천원)',
       '[제조]매출액(수익)(*)(IFRS)(천원)'],
      dtype='object')

In [380]:
df_11

,회사명,거래소코드,회계년도,[제조]자산(*)(IFRS연결),[제조]부채(*)(IFRS연결),[제조]자본(*)(IFRS연결)(천원),[제조]자산(*)(IFRS)(천원),[제조]부채(*)(IFRS)(천원),[제조]자본(*)(IFRS)(천원),[제조] 이익잉여금(결손금)(*)(IFRS연결)(천원),[제조]매출액(수익)(*)(IFRS연결)(천원),[제조] 이익잉여금(결손금)(*)(IFRS)(천원),[제조]매출액(수익)(*)(IFRS)(천원)
0,(주)CMG제약,58820,2011/12,27305198.0,9270949.0,18034249.0,27548539.0,9257624.0,18290915.0,-45215050.0,17751704.0,-44971257.0,17751704.0
1,(주)CMG제약,58820,2012/12,57108035.0,25517350.0,31590685.0,56988604.0,25386064.0,31602540.0,-52379991.0,16255389.0,-52368787.0,16255389.0
2,(주)CMG제약,58820,2013/12,55912563.0,6915281.0,48997281.0,55961620.0,6913407.0,49048213.0,-52201720.0,20402140.0,-52151440.0,20322140.0
3,(주)CMG제약,58820,2014/12,58068326.0,9065682.0,49002644.0,58127098.0,9060059.0,49067039.0,-52393918.0,22752584.0,-52330174.0,22752584.0
4,(주)CMG제약,58820,2015/12,56532821.0,9725933.0,46806888.0,56591972.0,9719267.0,46872705.0,-56413575.0,27041894.0,-56348409.0,27041894.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17482,흥구석유(주),24060,2018/12,NaN,NaN,NaN,75205581.0,4763313.0,70442269.0,NaN,NaN,34090738.0,166208303.0
17483,흥구석유(주),24060,2019/12,NaN,NaN,NaN,83661499.0,6660240.0,77001259.0,NaN,NaN,40649728.0,150668735.0
17484,흥구석유(주),24060,2020/12,NaN,NaN,NaN,83721348.0,4121163.0,79600184.0,NaN,NaN,43248653.0,114843735.0
17485,흥구석유(주),24060,2021/12,NaN,NaN,NaN,82647109.0,3751076.0,78896033.0,NaN,NaN,42544502.0,132213730.0
17486,흥구석유(주),24060,2022/12,NaN,NaN,NaN,93934616.0,13848317.0,80086299.0,NaN,NaN,43734768.0,146717690.0

In [381]:
df_ale.isna().sum()

회사명              0
거래소코드            0
회계년도             0
평균총자산_개별      2480
평균총부채_개별      2480
평균총자본_개별      2480
평균이익잉여금_개별    2480
평균총자산         6382
평균총부채         6382
평균총자본         6382
평균이익잉여금       6382
dtype: int64

연결 + 개별

In [382]:
# df_ale
_dict = {'평균총자산':'평균총자산_개별',
        '평균총부채':'평균총부채_개별',
        '평균총자본':'평균총자본_개별',
        '평균이익잉여금':'평균이익잉여금_개별',
        
        }
for i, j in _dict.items():
    df_ale[i].fillna(df_ale[j],inplace = True)
    df_ale.drop(columns=j, inplace=True)

df_ale

C:\Users\zino0\AppData\Local\Temp\ipykernel_31040\3188204435.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ale[i].fillna(df_ale[j],inplace = True)
C:\Users\zino0\AppData\Local\Temp\ipykernel_31040\3188204435.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ale.drop(columns=j, inplace=True)
C:\Users\zino0\AppData\Local\Temp\ipykernel_31040\3188204435.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ale[i].fillna(df_ale[j],inplace = True)
C:\Users\zino0\AppData\Local\Temp\ipykernel_31040\3188204435.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ale.drop(columns=j, inplace=True)
C:\Users\zino0\AppData\Local\Temp\ipykernel_31040\3188204435.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ale[i].fillna(df_ale[j],inplace = True)
C:\Users\zino0\AppData\Local\Temp\ipykernel_31040\3188204435.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ale.drop(columns=j, inplace=True)
C:\Users\zino0\AppData\Local\Temp\ipykernel_31040\3188204435.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ale[i].fillna(df_ale[j],inplace = True)
C:\Users\zino0\AppData\Local\Temp\ipykernel_31040\3188204435.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ale.drop(columns=j, inplace=True)

,회사명,거래소코드,회계년도,평균총자산,평균총부채,평균총자본,평균이익잉여금
0,(주)CMG제약,58820,2011/12,-1.0,-1.0,-1.0,-1.0
1,(주)CMG제약,58820,2012/12,42206616.5,17394149.5,24812467.0,-48797520.5
2,(주)CMG제약,58820,2013/12,56510299.0,16216315.5,40293983.0,-52290855.5
3,(주)CMG제약,58820,2014/12,56990444.5,7990481.5,48999962.5,-52297819.0
4,(주)CMG제약,58820,2015/12,57300573.5,9395807.5,47904766.0,-54403746.5
...,...,...,...,...,...,...,...
17482,흥구석유(주),24060,2018/12,77558818.5,7460492.5,70098326.5,33724098.5
17483,흥구석유(주),24060,2019/12,79433540.0,5711776.5,73721764.0,37370233.0
17484,흥구석유(주),24060,2020/12,83691423.5,5390701.5,78300721.5,41949190.5
17485,흥구석유(주),24060,2021/12,83184228.5,3936119.5,79248108.5,42896577.5
17486,흥구석유(주),24060,2022/12,88290862.5,8799696.5,79491166.0,43139635.0

In [383]:
df_ale.isna().sum()

회사명           0
거래소코드         0
회계년도          0
평균총자산      2371
평균총부채      2371
평균총자본      2371
평균이익잉여금    2371
dtype: int64

In [384]:
df_11.isna().sum()

회사명                                       0
거래소코드                                     0
회계년도                                      0
[제조]자산(*)(IFRS연결)                      6048
[제조]부채(*)(IFRS연결)                      6048
[제조]자본(*)(IFRS연결)(천원)                  6048
[제조]자산(*)(IFRS)(천원)                    1993
[제조]부채(*)(IFRS)(천원)                    1993
[제조]자본(*)(IFRS)(천원)                    1993
[제조]      이익잉여금(결손금)(*)(IFRS연결)(천원)    6048
[제조]매출액(수익)(*)(IFRS연결)(천원)             6048
[제조]   이익잉여금(결손금)(*)(IFRS)(천원)         1993
[제조]매출액(수익)(*)(IFRS)(천원)               1993
dtype: int64

In [385]:
# df_11

_dict = {'[제조]자산(*)(IFRS연결)':'[제조]자산(*)(IFRS)(천원)',
        '[제조]부채(*)(IFRS연결)':'[제조]부채(*)(IFRS)(천원)',
        '[제조]자본(*)(IFRS연결)(천원)':'[제조]자본(*)(IFRS)(천원)',
        '[제조]      이익잉여금(결손금)(*)(IFRS연결)(천원)':'[제조]   이익잉여금(결손금)(*)(IFRS)(천원)',
        }

for i, j in _dict.items():
    df_11[i].fillna(df_11[j],inplace = True)
    df_11.drop(columns=j, inplace=True)

df_11.drop(columns=['[제조]매출액(수익)(*)(IFRS연결)(천원)','[제조]매출액(수익)(*)(IFRS)(천원)'],inplace=True)

df_11

,회사명,거래소코드,회계년도,[제조]자산(*)(IFRS연결),[제조]부채(*)(IFRS연결),[제조]자본(*)(IFRS연결)(천원),[제조] 이익잉여금(결손금)(*)(IFRS연결)(천원)
0,(주)CMG제약,58820,2011/12,27305198.0,9270949.0,18034249.0,-45215050.0
1,(주)CMG제약,58820,2012/12,57108035.0,25517350.0,31590685.0,-52379991.0
2,(주)CMG제약,58820,2013/12,55912563.0,6915281.0,48997281.0,-52201720.0
3,(주)CMG제약,58820,2014/12,58068326.0,9065682.0,49002644.0,-52393918.0
4,(주)CMG제약,58820,2015/12,56532821.0,9725933.0,46806888.0,-56413575.0
...,...,...,...,...,...,...,...
17482,흥구석유(주),24060,2018/12,75205581.0,4763313.0,70442269.0,34090738.0
17483,흥구석유(주),24060,2019/12,83661499.0,6660240.0,77001259.0,40649728.0
17484,흥구석유(주),24060,2020/12,83721348.0,4121163.0,79600184.0,43248653.0
17485,흥구석유(주),24060,2021/12,82647109.0,3751076.0,78896033.0,42544502.0
17486,흥구석유(주),24060,2022/12,93934616.0,13848317.0,80086299.0,43734768.0

In [386]:
df_11.isna().sum()

회사명                                       0
거래소코드                                     0
회계년도                                      0
[제조]자산(*)(IFRS연결)                      1868
[제조]부채(*)(IFRS연결)                      1868
[제조]자본(*)(IFRS연결)(천원)                  1868
[제조]      이익잉여금(결손금)(*)(IFRS연결)(천원)    1864
dtype: int64

11' -> df_ale

In [387]:
df_11.info()
df_ale.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17487 entries, 0 to 17486
Data columns (total 7 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   회사명                                  17487 non-null  object
 1   거래소코드                                17487 non-null  int64
 2   회계년도                                 17487 non-null  object
 3   [제조]자산(*)(IFRS연결)                    15619 non-null  float64
 4   [제조]부채(*)(IFRS연결)                    15619 non-null  float64
 5   [제조]자본(*)(IFRS연결)(천원)                15619 non-null  float64
 6   [제조]      이익잉여금(결손금)(*)(IFRS연결)(천원)  15623 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 956.4+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 17487 entries, 0 to 17486
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   회사명      17487 non-null  object
 1   거래소코드    17487 non-null  int64
 2   회계년도     17487 non-null  object
 3   평균총자산    15116 non-null  float64
 4   평균총부채    15116 non-null  float64
 5   평균총자본    15116 non-null  float64
 6   평균이익잉여금  15116 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 1.1+ MB

In [388]:
df_all = pd.merge(df_ale, df_11, on = ['회사명', '거래소코드', '회계년도'], how = 'left')

In [389]:
# df_all.loc[df_all['회계년도'].str.contains('2011')]

_dict = {'평균총자산':'[제조]자산(*)(IFRS연결)',
         '평균총부채':'[제조]부채(*)(IFRS연결)',
         '평균총자본':'[제조]자본(*)(IFRS연결)(천원)',
         '평균이익잉여금':'[제조]      이익잉여금(결손금)(*)(IFRS연결)(천원)'
         }


for i,j in _dict.items():
    df_all.loc[df_all['회계년도'].str.contains('2011'),i] = df_all.loc[df_all['회계년도'].str.contains('2011'),j]

In [390]:
df_all

,회사명,거래소코드,회계년도,평균총자산,평균총부채,평균총자본,평균이익잉여금,[제조]자산(*)(IFRS연결),[제조]부채(*)(IFRS연결),[제조]자본(*)(IFRS연결)(천원),[제조] 이익잉여금(결손금)(*)(IFRS연결)(천원)
0,(주)CMG제약,58820,2011/12,27305198.0,9270949.0,18034249.0,-45215050.0,27305198.0,9270949.0,18034249.0,-45215050.0
1,(주)CMG제약,58820,2012/12,42206616.5,17394149.5,24812467.0,-48797520.5,57108035.0,25517350.0,31590685.0,-52379991.0
2,(주)CMG제약,58820,2013/12,56510299.0,16216315.5,40293983.0,-52290855.5,55912563.0,6915281.0,48997281.0,-52201720.0
3,(주)CMG제약,58820,2014/12,56990444.5,7990481.5,48999962.5,-52297819.0,58068326.0,9065682.0,49002644.0,-52393918.0
4,(주)CMG제약,58820,2015/12,57300573.5,9395807.5,47904766.0,-54403746.5,56532821.0,9725933.0,46806888.0,-56413575.0
...,...,...,...,...,...,...,...,...,...,...,...
17482,흥구석유(주),24060,2018/12,77558818.5,7460492.5,70098326.5,33724098.5,75205581.0,4763313.0,70442269.0,34090738.0
17483,흥구석유(주),24060,2019/12,79433540.0,5711776.5,73721764.0,37370233.0,83661499.0,6660240.0,77001259.0,40649728.0
17484,흥구석유(주),24060,2020/12,83691423.5,5390701.5,78300721.5,41949190.5,83721348.0,4121163.0,79600184.0,43248653.0
17485,흥구석유(주),24060,2021/12,83184228.5,3936119.5,79248108.5,42896577.5,82647109.0,3751076.0,78896033.0,42544502.0
17486,흥구석유(주),24060,2022/12,88290862.5,8799696.5,79491166.0,43139635.0,93934616.0,13848317.0,80086299.0,43734768.0

In [391]:
# -1.0 대체 잘 되었는지 확인
(df_all.loc[df_all['회계년도'].str.contains('2011/12')] == -1.0).sum()

회사명                                    0
거래소코드                                  0
회계년도                                   0
평균총자산                                  0
평균총부채                                  0
평균총자본                                  0
평균이익잉여금                                0
[제조]자산(*)(IFRS연결)                      0
[제조]부채(*)(IFRS연결)                      0
[제조]자본(*)(IFRS연결)(천원)                  0
[제조]      이익잉여금(결손금)(*)(IFRS연결)(천원)    0
dtype: int64

In [392]:
df_all.drop(columns = ['[제조]자산(*)(IFRS연결)', '[제조]부채(*)(IFRS연결)','[제조]자본(*)(IFRS연결)(천원)', '[제조]      이익잉여금(결손금)(*)(IFRS연결)(천원)'],\
    inplace = True)

In [393]:
df_all.columns

Index(['회사명', '거래소코드', '회계년도', '평균총자산', '평균총부채', '평균총자본', '평균이익잉여금'], dtype='object')

df_all + df_mk

In [394]:
df_all.info()
df_mk.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17487 entries, 0 to 17486
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   회사명      17487 non-null  object
 1   거래소코드    17487 non-null  int64
 2   회계년도     17487 non-null  object
 3   평균총자산    14914 non-null  float64
 4   평균총부채    14914 non-null  float64
 5   평균총자본    14914 non-null  float64
 6   평균이익잉여금  14914 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 1.1+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 17487 entries, 0 to 17486
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   회사명_x   17487 non-null  object
 1   거래소코드   17487 non-null  int64
 2   회계년도    17487 non-null  datetime64[ns]
 3   시가총액    14013 non-null  float64
 4   연도      17487 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 819.7+ KB

In [395]:
df_mk.rename(columns = {'회사명_x':'회사명'}, inplace = True)

In [396]:
df_all['회계년도'] = pd.to_datetime(df_all['회계년도'], format = '%Y/%m')

In [397]:
df_all

,회사명,거래소코드,회계년도,평균총자산,평균총부채,평균총자본,평균이익잉여금
0,(주)CMG제약,58820,2011-12-01,27305198.0,9270949.0,18034249.0,-45215050.0
1,(주)CMG제약,58820,2012-12-01,42206616.5,17394149.5,24812467.0,-48797520.5
2,(주)CMG제약,58820,2013-12-01,56510299.0,16216315.5,40293983.0,-52290855.5
3,(주)CMG제약,58820,2014-12-01,56990444.5,7990481.5,48999962.5,-52297819.0
4,(주)CMG제약,58820,2015-12-01,57300573.5,9395807.5,47904766.0,-54403746.5
...,...,...,...,...,...,...,...
17482,흥구석유(주),24060,2018-12-01,77558818.5,7460492.5,70098326.5,33724098.5
17483,흥구석유(주),24060,2019-12-01,79433540.0,5711776.5,73721764.0,37370233.0
17484,흥구석유(주),24060,2020-12-01,83691423.5,5390701.5,78300721.5,41949190.5
17485,흥구석유(주),24060,2021-12-01,83184228.5,3936119.5,79248108.5,42896577.5
17486,흥구석유(주),24060,2022-12-01,88290862.5,8799696.5,79491166.0,43139635.0

In [398]:
df_mk

            회사명  거래소코드       회계년도          시가총액    연도
0      (주)CMG제약  58820 2014-12-01  7.900370e+10  2014
1      (주)CMG제약  58820 2018-12-01  4.611375e+11  2018
2      (주)CMG제약  58820 2019-12-01  5.902920e+11  2019
3      (주)CMG제약  58820 2020-12-01  8.027972e+11  2020
4      (주)CMG제약  58820 2017-12-01  6.794564e+11  2017
...         ...    ...        ...           ...   ...
17482   흥구석유(주)  24060 2022-12-01  8.520000e+10  2022
17483   흥구석유(주)  24060 2013-12-01  3.000000e+10  2013
17484   흥구석유(주)  24060 2018-12-01  4.057500e+10  2018
17485   흥구석유(주)  24060 2016-12-01  5.137500e+10  2016
17486   흥구석유(주)  24060 2015-12-01  4.560000e+10  2015

[17487 rows x 5 columns]

In [399]:
df_altman =pd.merge(df_all, df_mk, on = ['회사명','거래소코드', '회계년도'], how = 'left')

In [400]:
df_altman['회계년도'] = df_altman['회계년도'].dt.strftime('%Y/%m')

Altman

Altman 변수확보

In [401]:
k2_score = df_altman.iloc[:, 0:3]
k2_score

            회사명  거래소코드     회계년도
0      (주)CMG제약  58820  2011/12
1      (주)CMG제약  58820  2012/12
2      (주)CMG제약  58820  2013/12
3      (주)CMG제약  58820  2014/12
4      (주)CMG제약  58820  2015/12
...         ...    ...      ...
17482   흥구석유(주)  24060  2018/12
17483   흥구석유(주)  24060  2019/12
17484   흥구석유(주)  24060  2020/12
17485   흥구석유(주)  24060  2021/12
17486   흥구석유(주)  24060  2022/12

[17487 rows x 3 columns]

In [402]:
# 1.기업규모
# 자산 단위 변경 : 1,000 -> 1,000,000
k2_score['log총자산(백만원)'] = np.log(df_altman['평균총자산']/1000)

In [403]:
df_altman.head()

,회사명,거래소코드,회계년도,평균총자산,평균총부채,평균총자본,평균이익잉여금,시가총액,연도
0,(주)CMG제약,58820,2011/12,27305198.0,9270949.0,18034249.0,-45215050.0,3.429916e+10,2011
1,(주)CMG제약,58820,2012/12,42206616.5,17394149.5,24812467.0,-48797520.5,8.781397e+10,2012
2,(주)CMG제약,58820,2013/12,56510299.0,16216315.5,40293983.0,-52290855.5,8.073624e+10,2013
3,(주)CMG제약,58820,2014/12,56990444.5,7990481.5,48999962.5,-52297819.0,7.900370e+10,2014
4,(주)CMG제약,58820,2015/12,57300573.5,9395807.5,47904766.0,-54403746.5,1.863072e+11,2015

---
### <긴급>
매출액 컬럼 확보

In [404]:
df_sale_0 = pd.concat([df_sre['[제조]매출액(수익)(*)(IFRS연결)(천원)'], df_sre_each['[제조]매출액(수익)(*)(IFRS)(천원)']], axis = 1)

In [405]:
df_sale_0.columns = ['매출액(천원)', '매출액_개별']
df_sale_0['매출액(천원)'] = df_sale_0['매출액(천원)'].fillna(df_sale_0['매출액_개별'])

In [406]:
df_sale=df_sale_0.drop('매출액_개별', axis = 1)

In [407]:
df_altman = pd.concat([df_altman, df_sale], axis = 1)

In [408]:
# 2. 총자산회전율

k2_score['총자산회전율(log)'] = np.log(df_altman['매출액(천원)']/df_altman['평균총자산'])

c:\Users\zino0\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [409]:
df_altman

,회사명,거래소코드,회계년도,평균총자산,평균총부채,평균총자본,평균이익잉여금,시가총액,연도,매출액(천원)
0,(주)CMG제약,58820,2011/12,27305198.0,9270949.0,18034249.0,-45215050.0,3.429916e+10,2011,17751704.0
1,(주)CMG제약,58820,2012/12,42206616.5,17394149.5,24812467.0,-48797520.5,8.781397e+10,2012,16255389.0
2,(주)CMG제약,58820,2013/12,56510299.0,16216315.5,40293983.0,-52290855.5,8.073624e+10,2013,20402140.0
3,(주)CMG제약,58820,2014/12,56990444.5,7990481.5,48999962.5,-52297819.0,7.900370e+10,2014,22752584.0
4,(주)CMG제약,58820,2015/12,57300573.5,9395807.5,47904766.0,-54403746.5,1.863072e+11,2015,27041894.0
...,...,...,...,...,...,...,...,...,...,...
17482,흥구석유(주),24060,2018/12,77558818.5,7460492.5,70098326.5,33724098.5,4.057500e+10,2018,166208303.0
17483,흥구석유(주),24060,2019/12,79433540.0,5711776.5,73721764.0,37370233.0,8.040000e+10,2019,150668735.0
17484,흥구석유(주),24060,2020/12,83691423.5,5390701.5,78300721.5,41949190.5,1.083000e+11,2020,114843735.0
17485,흥구석유(주),24060,2021/12,83184228.5,3936119.5,79248108.5,42896577.5,1.074000e+11,2021,132213730.0
17486,흥구석유(주),24060,2022/12,88290862.5,8799696.5,79491166.0,43139635.0,8.520000e+10,2022,146717690.0

In [410]:
# 3. 누적수익성 
k2_score['누적수익성'] = df_altman['평균이익잉여금']/df_altman['평균총자산']

In [411]:
k2_score

            회사명  거래소코드     회계년도  log총자산(백만원)  총자산회전율(log)     누적수익성
0      (주)CMG제약  58820  2011/12    10.214832    -0.430596 -1.655914
1      (주)CMG제약  58820  2012/12    10.650332    -0.954153 -1.156158
2      (주)CMG제약  58820  2013/12    10.942178    -1.018783 -0.925333
3      (주)CMG제약  58820  2014/12    10.950639    -0.918205 -0.917659
4      (주)CMG제약  58820  2015/12    10.956066    -0.750923 -0.949445
...         ...    ...      ...          ...          ...       ...
17482   흥구석유(주)  24060  2018/12    11.258792     0.762205  0.434820
17483   흥구석유(주)  24060  2019/12    11.282676     0.640163  0.470459
17484   흥구석유(주)  24060  2020/12    11.334892     0.316436  0.501236
17485   흥구석유(주)  24060  2021/12    11.328813     0.463362  0.515682
17486   흥구석유(주)  24060  2022/12    11.388392     0.507874  0.488608

[17487 rows x 6 columns]

In [412]:
# 4. 재무구조
# 시가총액 단위변경 : 1 -> 1,000 : 부채가 천원 단위이므로 단위 맞춰주기 위함
k2_score['재무구조'] = (df_altman['시가총액']/1000) / df_altman['평균총부채']

In [413]:
col_order = ['회사명', '거래소코드', '회계년도','log총자산(백만원)','총자산회전율(log)', '누적수익성', '재무구조']

In [414]:
k2_score = k2_score.reindex(columns = col_order)
k2_score

            회사명  거래소코드     회계년도  log총자산(백만원)  총자산회전율(log)     누적수익성       재무구조
0      (주)CMG제약  58820  2011/12    10.214832    -0.430596 -1.655914   3.699639
1      (주)CMG제약  58820  2012/12    10.650332    -0.954153 -1.156158   5.048477
2      (주)CMG제약  58820  2013/12    10.942178    -1.018783 -0.925333   4.978704
3      (주)CMG제약  58820  2014/12    10.950639    -0.918205 -0.917659   9.887227
4      (주)CMG제약  58820  2015/12    10.956066    -0.750923 -0.949445  19.828757
...         ...    ...      ...          ...          ...       ...        ...
17482   흥구석유(주)  24060  2018/12    11.258792     0.762205  0.434820   5.438649
17483   흥구석유(주)  24060  2019/12    11.282676     0.640163  0.470459  14.076181
17484   흥구석유(주)  24060  2020/12    11.334892     0.316436  0.501236  20.090150
17485   흥구석유(주)  24060  2021/12    11.328813     0.463362  0.515682  27.285757
17486   흥구석유(주)  24060  2022/12    11.388392     0.507874  0.488608   9.682152

[17487 rows x 7 columns]

# K2_score 적용

In [415]:
k2_score.columns

Index(['회사명', '거래소코드', '회계년도', 'log총자산(백만원)', '총자산회전율(log)', '누적수익성', '재무구조'], dtype='object')

In [416]:
k2_series = (-18.696) + 1.501*k2_score['log총자산(백만원)'] + 2.706*k2_score['총자산회전율(log)'] + 19.760*k2_score['누적수익성'] + 1.146*k2_score['재무구조']

In [417]:
k2_score['K2_score'] = k2_series

In [418]:
k2_score

,회사명,거래소코드,회계년도,log총자산(백만원),총자산회전율(log),누적수익성,재무구조,K2_score
0,(주)CMG제약,58820,2011/12,10.214832,-0.430596,-1.655914,3.699639,-33.009796
1,(주)CMG제약,58820,2012/12,10.650332,-0.954153,-1.156158,5.048477,-22.351917
2,(주)CMG제약,58820,2013/12,10.942178,-1.018783,-0.925333,4.978704,-17.607606
3,(주)CMG제약,58820,2014/12,10.950639,-0.918205,-0.917659,9.887227,-11.545942
4,(주)CMG제약,58820,2015/12,10.956066,-0.750923,-0.949445,19.828757,-0.320222
...,...,...,...,...,...,...,...,...
17482,흥구석유(주),24060,2018/12,11.258792,0.762205,0.434820,5.438649,15.090702
17483,흥구석유(주),24060,2019/12,11.282676,0.640163,0.470459,14.076181,25.399153
17484,흥구석유(주),24060,2020/12,11.334892,0.316436,0.501236,20.090150,32.101691
17485,흥구석유(주),24060,2021/12,11.328813,0.463362,0.515682,27.285757,41.021752
17486,흥구석유(주),24060,2022/12,11.388392,0.507874,0.488608,9.682152,20.522926

In [419]:
# K2 score 범위 확인 

## 부실 가능성 심각
bad = (k2_score['K2_score'] < (-2.3)).sum()

## 판정 보류
neutral = ((k2_score['K2_score'] >= -2.3) & (k2_score['K2_score']<=0.75)).sum()

## 건전판정
good = (k2_score['K2_score'] > 0.75).sum()

###
agg = bad + neutral + good

print(f'부실 비중 : {np.round(((bad/agg)*100),4)}%')
print(f'보류 비중 : {np.round(((neutral/agg)*100),4)}%')
print(f'건전 비중 : {np.round(((good/agg)*100),4)}%')

부실 비중 : 17.7231%
보류 비중 : 7.9339%
건전 비중 : 74.3431%

---

In [420]:
print(bad)
print(neutral)
print(good)

2455
1099
10298

In [421]:
k2_score.isna().sum()

회사명               0
거래소코드             0
회계년도              0
log총자산(백만원)    2573
총자산회전율(log)    2576
누적수익성          2573
재무구조           3635
K2_score       3635
dtype: int64

In [422]:
# k2_score.to_excel('./K2_score.xlsx')